name: Create release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Create release zip
      run: Compress-Archive -Path target/release/injector.exe, target/release/patch.dll -DestinationPath "release-${{ github.ref_name }}.zip"
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release create "$tag"
        "release.zip"
        --repo="$GITHUB_REPOSITORY"
        --generate-notes
        --title "Version ${tag#v}"
